import React from "react";
import "./ServiceAdvisor.css";
const rows=[
['APT-0881','17 Aug 2026','09:00 AM','Vikram Singh','Fortuner UP-32-GH-1190','Suspension & Tyres','Walk-in','Bay 3','—','Ramesh K.','Confirmed','status-confirmed'],
['APT-0882','17 Aug 2026','10:30 AM','Anjali Tiwari','Verna MH-04-RT-6621','Full Service','Online','Bay 1','✓','Ramesh K.','Confirmed','status-confirmed'],
['APT-0883','17 Aug 2026','12:00 PM','Karan Malhotra','Nexon TN-09-HH-2210','AC Service','Online','Bay 2','—','Sunita P.','In Progress','status-progress'],
['APT-0884','17 Aug 2026','02:00 PM','Sonal Gupta','WagonR GJ-01-AB-5541','Basic Service','Walk-in','Bay 4','—','Ramesh K.','Pending','status-pending'],
['APT-0885','18 Aug 2026','09:30 AM','Arjun Mehta','Swift MH-12-AB-4521','Battery Replacement','Online','Bay 1','—','Sunita P.','Confirmed','status-confirmed'],
['APT-0886','18 Aug 2026','11:00 AM','Priya Sharma','Creta DL-01-CZ-9834','Tyre Rotation','Online','Bay 2','—','Ramesh K.','Confirmed','status-confirmed'],
['APT-0887','19 Aug 2026','10:00 AM','Neha Joshi','City MH-14-PQ-3356','Denting & Painting','Pickup/Drop','Bay 3','✓','Sunita P.','Pending','status-pending'],
];
export default function Appointments(){return <div className="sa-page"><div className="sa-page-head"><div><h1 className="sa-title">APPOINTMENTS</h1></div><button className="sa-primary">+ NEW APPOINTMENT</button></div><div className="sa-stats"><div className="sa-stat"><div className="sa-stat-label">Today</div><div className="sa-stat-value">4</div><div className="sa-stat-note">2 confirmed · 1 pending</div></div><div className="sa-stat"><div className="sa-stat-label">Tomorrow</div><div className="sa-stat-value" style={{color:'var(--sa-lime)'}}>2</div></div><div className="sa-stat"><div className="sa-stat-label">This Week</div><div className="sa-stat-value">12</div></div><div className="sa-stat"><div className="sa-stat-label">Pickup/Drop</div><div className="sa-stat-value">3</div><div className="sa-stat-note">requiring logistics</div></div></div><div className="sa-date-tabs"><button className="sa-tab active">ALL DAYS</button><button className="sa-tab">17 AUG</button><button className="sa-tab">18 AUG</button><button className="sa-tab">19 AUG</button></div><div className="sa-wide-table"><table className="sa-table"><thead><tr><th>ID</th><th>Date & Time</th><th>Customer</th><th>Vehicle</th><th>Service</th><th>Type</th><th>Bay</th><th>Pickup</th><th>Advisor</th><th>Status</th><th></th></tr></thead><tbody>{rows.map(r=><tr key={r[0]}><td className="sa-id">{r[0]}</td><td><strong>{r[1]}</strong><br/><small>{r[2]}</small></td><td><strong>{r[3]}</strong></td><td>{r[4]}</td><td><strong>{r[5]}</strong></td><td>{r[6]}</td><td>{r[7]}</td><td style={{color:r[8]==='✓'?'var(--sa-lime)':undefined}}>{r[8]}</td><td>{r[9]}</td><td><span className={`sa-status ${r[11]}`}>{r[10]}</span></td><td><button className="sa-details">Edit</button></td></tr>)}</tbody></table></div></div>}
