import React from "react";
import "./ServiceAdvisor.css";
const jobs=[
['JC-2408','Arjun Mehta','MH-12-AB-4521 | Swift','Engine Overhaul','Ravi Kumar','In Repair','Today 5:00 PM','₹18,500','status-repair',3],
['JC-2407','Priya Sharma','DL-01-CZ-9834 | Creta','Full Service','Amit Patel','Quality Check','Today 3:30 PM','₹8,200','status-qc',4],
['JC-2406','Rohit Desai','GJ-05-XY-7712 | Innova','AC Repair + Service','Suresh Nair','Delivered','Delivered','₹12,400','status-delivered',5],
['JC-2405','Neha Joshi','MH-14-PQ-3356 | City','Brake Replacement','Ravi Kumar','Inspection','Today 6:00 PM','₹4,800','status-inspection',2],
['JC-2404','Vikram Singh','UP-32-GH-1190 | Fortuner','Suspension + Tyres','Amit Patel','Received','Tomorrow 12:00 PM','₹32,000','status-received',1],
];
export default function JobCards(){return <div className="sa-page"><div className="sa-page-head"><div><h1 className="sa-title">JOB CARDS</h1></div><button className="sa-primary">+ NEW JOB CARD</button></div><div className="sa-stats"><div className="sa-stat"><div className="sa-stat-label">Total Today</div><div className="sa-stat-value">14</div></div><div className="sa-stat"><div className="sa-stat-label">In Repair</div><div className="sa-stat-value" style={{color:'var(--sa-lime)'}}>4</div></div><div className="sa-stat"><div className="sa-stat-label">QC</div><div className="sa-stat-value">2</div></div><div className="sa-stat"><div className="sa-stat-label">Delivered</div><div className="sa-stat-value">6</div></div><div className="sa-stat"><div className="sa-stat-label">Overdue</div><div className="sa-stat-value">1</div></div></div><div className="sa-date-tabs"><button className="sa-tab active">ALL</button><button className="sa-tab">RECEIVED</button><button className="sa-tab">INSPECTION</button><button className="sa-tab">REPAIR</button><button className="sa-tab">QC</button><button className="sa-tab">DELIVERED</button></div><div className="sa-job-list">{jobs.map(j=><article className="sa-job" key={j[0]}><div className="sa-job-top"><div><div className="sa-id">{j[0]}</div><div className="sa-job-value" style={{fontSize:14,marginTop:4}}>{j[1]}</div><div className="sa-job-sub">{j[2]}</div></div><div><div className="sa-job-label">Service</div><div className="sa-job-value">{j[3]}</div><div className="sa-job-sub">Mechanic: {j[4]}</div></div><div><span className={`sa-status ${j[8]}`}>{j[5]}</span></div><div><div className="sa-job-label">{j[6]==='Delivered'?'':'ETA'}</div><div className="sa-job-sub">{j[6]}</div></div><div><div className="sa-job-amount">{j[7]}</div><button className="sa-details">Details</button></div></div><div className="sa-stepper">{['Received','Inspection','In Repair','QC','Delivered'].map((s,i)=><div key={s} className={`sa-step ${i<j[9]?'done':''}`}>{s}</div>)}</div></article>)}</div></div>}
