import React from "react";
import "./ServiceAdvisor.css";
const packages=[
{tag:'BASIC',name:'BASIC SERVICE',duration:'2–3 hrs',price:'₹2,499',features:['Engine oil change (3L)','Oil filter replacement','Air filter check','Tyre pressure check','Battery check','Exterior wash'],chips:['Engine Oil 3L','Oil Filter']},
{tag:'FULL',name:'FULL SERVICE',duration:'4–5 hrs',price:'₹5,999',popular:true,features:['All Basic Service items','AC filter replacement','Brake inspection','Steering & suspension check','Wiper blade check','Interior vacuum','Wheel alignment check','Spark plug inspection'],chips:['Engine Oil 5L','Oil Filter','AC Filter']},
{tag:'PREMIUM',name:'PREMIUM SERVICE',duration:'6–8 hrs',price:'₹10,999',features:['All Full Service items','Spark plug replacement (set 4)','Coolant flush & refill','Brake fluid change','Fuel injector cleaning','Throttle body cleaning','TPMS reset','OBD diagnostic scan','Full engine bay cleaning'],chips:['Engine Oil 5L','Oil Filter','AC Filter','Spark Plugs Set','Coolant 1L']},
{tag:'AMC',name:'AMC PACKAGE',duration:'12 months',price:'₹18,999',features:['2× Full Service visits','1× Premium Service visit','Priority appointment booking','Free towing (2 calls/year)','Free car wash (12 visits)','WhatsApp service updates','Dedicated service advisor','Loyalty reward points'],chips:['All consumables included']},
];
export default function Packages(){return <div className="sa-page"><div className="sa-page-head"><div><h1 className="sa-title">SERVICE PACKAGES</h1></div><button className="sa-primary">+ NEW PACKAGE</button></div><div className="sa-stats"><div className="sa-stat"><div className="sa-stat-label">Active Packages</div><div className="sa-stat-value">4</div></div><div className="sa-stat"><div className="sa-stat-label">AMC Customers</div><div className="sa-stat-value" style={{color:'var(--sa-lime)'}}>38</div></div><div className="sa-stat"><div className="sa-stat-label">Monthly Revenue</div><div className="sa-stat-value">₹1.8L</div><div className="sa-stat-note">from packages</div></div><div className="sa-stat"><div className="sa-stat-label">Avg Package Value</div><div className="sa-stat-value">₹9,624</div></div></div><div className="sa-package-grid">{packages.map((p)=><div className={`sa-package ${p.popular?'popular':''}`} key={p.name} style={{position:'relative'}}>{p.popular&&<div className="sa-popular">POPULAR</div>}<div className="sa-package-head"><div className="sa-package-icon">🔧</div><div className="sa-package-tag">{p.tag}</div><div className="sa-package-name">{p.name}</div><div className="sa-package-duration">{p.duration}</div></div><div className="sa-package-price">{p.price}</div><div className="sa-package-gst">+ 18% GST</div><div className="sa-package-body">{p.features.map(f=><div className="sa-feature" key={f}>{f}</div>)}<div className="sa-includes">Includes</div>{p.chips.map(c=><span className="sa-chip" key={c}>{c}</span>)}</div><div className="sa-package-footer"><button className="sa-apply">APPLY PACKAGE</button><button className="sa-edit">Edit</button></div></div>)}</div></div>}
