import React, { useMemo, useState } from "react";
import "./ServiceAdvisor.css";
const rows=[
['MH-12-AB-4521','Swift VXI','Maruti Suzuki','2021','Arjun Mehta','28,400 km','31 Mar 2027','17 Aug 2026','In Service','status-repair'],
['DL-01-CZ-9834','Creta SX','Hyundai','2022','Priya Sharma','42,100 km','15 Jun 2027','17 Aug 2026','In Service','status-repair'],
['GJ-05-XY-7712','Innova Crysta','Toyota','2019','Rohit Desai','84,200 km','28 Feb 2027','16 Aug 2026','Delivered','status-delivered'],
['MH-14-PQ-3356','City ZX','Honda','2020','Neha Joshi','38,900 km','10 Sep 2026 ⚠','17 Aug 2026','In Service','status-repair'],
['UP-32-GH-1190','Fortuner 4x4','Toyota','2023','Vikram Singh','18,700 km','22 Jan 2028','15 Aug 2026','Waiting','status-inspection'],
['KA-03-MN-5567','Baleno Delta','Maruti Suzuki','2018','Kavita Rao','61,000 km','05 May 2027','16 Aug 2026','Delivered','status-delivered'],
['MH-09-ZZ-3344','Polo TSI','Volkswagen','2020','Divya Kapoor','44,800 km','14 Dec 2026','10 Aug 2026','Delivered','status-delivered'],
];
export default function Vehicles(){const[q,setQ]=useState('');const data=useMemo(()=>rows.filter(r=>r.join(' ').toLowerCase().includes(q.toLowerCase())),[q]);return <div className="sa-page"><div className="sa-page-head"><div><h1 className="sa-title">VEHICLES</h1></div><button className="sa-primary">+ REGISTER VEHICLE</button></div><div className="sa-stats"><div className="sa-stat"><div className="sa-stat-label">Total Vehicles</div><div className="sa-stat-value">7</div></div><div className="sa-stat"><div className="sa-stat-label">In Service</div><div className="sa-stat-value" style={{color:'var(--sa-lime)'}}>3</div></div><div className="sa-stat"><div className="sa-stat-label">Insurance Expiring</div><div className="sa-stat-value">2</div><div className="sa-stat-note">within 60 days</div></div><div className="sa-stat"><div className="sa-stat-label">Avg Mileage</div><div className="sa-stat-value">44K km</div></div></div><div className="sa-toolbar"><input className="sa-search" placeholder="Search by reg, owner, model..." value={q} onChange={e=>setQ(e.target.value)}/><select className="sa-filter"><option>All Fuel Types</option></select><select className="sa-filter"><option>All Statuses</option></select></div><div className="sa-wide-table"><table className="sa-table"><thead><tr><th>Reg. No.</th><th>Make & Model</th><th>Year</th><th>Owner</th><th>Mileage</th><th>Insurance Expiry</th><th>Last Service</th><th>Status</th><th></th></tr></thead><tbody>{data.map(r=><tr key={r[0]}><td className="sa-id">{r[0]}</td><td><strong>{r[1]}</strong><br/><small>{r[2]}</small></td><td>{r[3]}</td><td><strong>{r[4]}</strong></td><td><strong>{r[5]}</strong></td><td style={{color:r[6].includes('⚠')?'#eaa735':undefined}}>{r[6]}</td><td>{r[7]}</td><td><span className={`sa-status ${r[9]}`}>{r[8]}</span></td><td><button className="sa-details">View</button></td></tr>)}</tbody></table></div></div>}
